### ISSUE TITLE
Add Qulice to project

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/self-ev-rules#3]

**Comment by 0pdd** [comment]
@nergal-perm 8 puzzles [#10](https://github.com/nergal-perm/self-ev-rules/issues/10), [#11](https://github.com/nergal-perm/self-ev-rules/issues/11), [#12](https://github.com/nergal-perm/self-ev-rules/issues/12), [#13](https://github.com/nergal-perm/self-ev-rules/issues/13), [#14](https://github.com/nergal-perm/self-ev-rules/issues/14), [#7](https://github.com/nergal-perm/self-ev-rules/issues/7), [#8](https://github.com/nergal-perm/self-ev-rules/issues/8), [#9](https://github.com/nergal-perm/self-ev-rules/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 7 puzzles [#10](https://github.com/nergal-perm/self-ev-rules/issues/10), [#11](https://github.com/nergal-perm/self-ev-rules/issues/11), [#12](https://github.com/nergal-perm/self-ev-rules/issues/12), [#13](https://github.com/nergal-perm/self-ev-rules/issues/13), [#14](https://github.com/nergal-perm/self-ev-rules/issues/14), [#7](https://github.com/nergal-perm/self-ev-rules/issues/7), [#8](https://github.com/nergal-perm/self-ev-rules/issues/8) are still not solved; solved: [#9](https://github.com/nergal-perm/self-ev-rules/issues/9).

**Comment by nergal-perm** [comment]
Reopening in order for 0pdd to make its work

**Comment by 0pdd** [comment]
@nergal-perm 6 puzzles [#11](https://github.com/nergal-perm/self-ev-rules/issues/11), [#12](https://github.com/nergal-perm/self-ev-rules/issues/12), [#13](https://github.com/nergal-perm/self-ev-rules/issues/13), [#14](https://github.com/nergal-perm/self-ev-rules/issues/14), [#7](https://github.com/nergal-perm/self-ev-rules/issues/7), [#8](https://github.com/nergal-perm/self-ev-rules/issues/8) are still not solved; solved: [#10](https://github.com/nergal-perm/self-ev-rules/issues/10), [#9](https://github.com/nergal-perm/self-ev-rules/issues/9).

**Comment by 0pdd** [comment]
@nergal-perm 5 puzzles [#11](https://github.com/nergal-perm/self-ev-rules/issues/11), [#12](https://github.com/nergal-perm/self-ev-rules/issues/12), [#13](https://github.com/nergal-perm/self-ev-rules/issues/13), [#14](https://github.com/nergal-perm/self-ev-rules/issues/14), [#8](https://github.com/nergal-perm/self-ev-rules/issues/8) are still not solved; solved: [#10](https://github.com/nergal-perm/self-ev-rules/issues/10), [#7](https://github.com/nergal-perm/self-ev-rules/issues/7), [#9](https://github.com/nergal-perm/self-ev-rules/issues/9).

**Comment by 0pdd** [comment]
@nergal-perm all 8 puzzles are solved here: [#10](https://github.com/nergal-perm/self-ev-rules/issues/10), [#11](https://github.com/nergal-perm/self-ev-rules/issues/11), [#12](https://github.com/nergal-perm/self-ev-rules/issues/12), [#13](https://github.com/nergal-perm/self-ev-rules/issues/13), [#14](https://github.com/nergal-perm/self-ev-rules/issues/14), [#7](https://github.com/nergal-perm/self-ev-rules/issues/7), [#8](https://github.com/nergal-perm/self-ev-rules/issues/8), [#9](https://github.com/nergal-perm/self-ev-rules/issues/9).
